version: "3.4"

volumes:
  postgresql:
  mysql-db:

services:
  postgresql-dev:
    image: postgres:9.6.15
    volumes:
      - postgresql:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=ombulabs
      - POSTGRES_PASSWORD=
  
  mysql-dev:
    image: mysql:5.7
    restart: always
    environment:
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'ombulabs'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - mysql-db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
        - '8080:80'
    restart: always
    environment:
        PMA_HOST: mysql-dev
    depends_on:
        - mysql-dev

  apache-environment-dev:
    container_name: php-apache
    image: php:8.0-apache
    volumes:
      - ~/dev/work/php:/var/www/html/
    ports:
      - 8000:80

  memcached-dev:
    image: memcached
    ports:
      - 11211:11211

  redis-dev:
    image: redis:5.0.6-alpine
    ports:
      - 6379:6379
